<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>nvr-platform</artifactId>
        <version>4.2.0.RELEASE</version>
    </parent>
    <artifactId>nvr-api</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>nvr-api-dahua</module>
        <module>nvr-api-gb28181</module>
        <module>nvr-api-haikang</module>
        <module>nvr-api-jt1078</module>
        <module>nvr-api-onvif</module>
        <module>nvr-api-haikang-isup</module>
        <module>nvr-api-qs</module>
        <module>nvr-api-zlm</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springblade</groupId>
                <artifactId>blade-common</artifactId>
                <version>4.2.0.RELEASE</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>org.springblade</groupId>
                <artifactId>nvr-common</artifactId>
                <version>4.2.0.RELEASE</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
