<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-base-facade</artifactId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>org.springblade</groupId>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-base-boot-impl</artifactId>
    <name>${project.artifactId}</name>
    <description>基础服务-单体版实现</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-base-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-base-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

    </dependencies>
</project>
