<?xml version="1.0" encoding="UTF-8"?>
<!-- MQS 控制器：REST API 端点 -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-mqs</artifactId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-mqs-controller</artifactId>
    <name>${project.artifactId}</name>
    <description>MQS Controller</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-mqs-biz</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-mqs-biz-bus</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-starter-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>jboss-annotations-api_1.3_spec</artifactId>
                    <groupId>org.jboss.spec.jakarta.annotation</groupId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
