<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>nvr-platform</artifactId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>nvr-common</artifactId>
    <name>nvr-common</name>
    <description>存放 NVR 全局常量、业务枚举、通用工具类、统一异常、基础 DTO 实体</description>

    <properties>
        <module.name>nvr.common</module.name>
    </properties>

    <dependencies>

        <!-- ===== 1. BladeX 底层基础工具 ===== -->
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-core-tool</artifactId>
        </dependency>

        <!-- ===== 2. Feign 远程调用 ===== -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-core</artifactId>
        </dependency>

        <!-- ===== 3. Lombok（编译期） ===== -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>
