package org.springblade.modules.iot.protocol.vo.param;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import java.io.Serializable;

/**
 * -----------------------------------------------------------------------------
 * File Name: OpenAiChatRequestParam
 * -----------------------------------------------------------------------------
 * Description:
 * OpenAiChatRequest
 * -----------------------------------------------------------------------------
 *
 * @author xiaonannet
 * @version 1.0
 * -----------------------------------------------------------------------------
 * Revision History:
 * Date         Author          Version     Description
 * --------      --------     -------   --------------------
 * 2023/12/12       xiaonannet        1.0        Initial creation
 * -----------------------------------------------------------------------------
 * @email 13733918655@163.com
 * @date 2023/12/12 23:20
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode
@Builder
@Schema(title = "OpenAiChatRequest", description = "Request parameters for OpenAI Chat API")
public class OpenAiChatRequestParam implements Serializable {
    private static final long serialVersionUID = 1L;

    @Schema(description = "The unique session ID generated by OpenAI.")
    private String id;

    @Schema(description = "The model to use for this chat (e.g., gpt-3.5-turbo)")
    @NotEmpty(message = "Model is required")
    private String model;

    @Schema(description = "Content of the message to be processed")
    @NotEmpty(message = "Content cannot be null")
    @Size(min = 1, max = 1000, message = "Content must be between 1 and 1000 characters")
    private String content;

    @Schema(description = "API Key for OpenAI")
    private String apiKey;

    @Schema(description = "API Host for OpenAI")
    private String apiHost;

}
