<?xml version="1.0" encoding="UTF-8"?>
<!-- Broker 控制器：REST API 端点 -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-broker</artifactId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-broker-controller</artifactId>
    <name>${project.artifactId}</name>
    <description>Broker Controller</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-broker-biz</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-starter-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.mqttsnet.basic</groupId>
            <artifactId>thinglinks-kafka-starter</artifactId>
            <version>1.0.8.3</version>
        </dependency>
    </dependencies>
</project>
