<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>nvr-api</artifactId>
        <version>4.2.0.RELEASE</version>
    </parent>
    <artifactId>nvr-api-dahua</artifactId>
    <description>
        nvr-api-dahua 大华SDK接口模块
    </description>
    <properties>
        <!-- 增加自动模块名称，解决空模块名报错 -->
        <module.name>nvr.api.dahua</module.name>
    </properties>
    <dependencies>
        <!-- IoT Common -->

        <!-- 原生Feign，无需SpringCloud -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-openfeign-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>nvr-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-common</artifactId>
        </dependency>
    </dependencies>

</project>
