<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>iot-rule</artifactId>
        <groupId>org.springblade</groupId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-rule-facade</artifactId>
    <name>${project.artifactId}</name>
    <description>规则引擎服务-门面模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>iot-rule-api</module>
        <module>iot-rule-boot-impl</module>
        <module>iot-rule-cloud-impl</module>
    </modules>
</project>
