-- Kafka配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (626, 1, '主机地址', 'host', 'databridge_kafka_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入Kafka主机地址"}'),
       (627, 2, '端口', 'port', 'databridge_kafka_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":9092}'),
       (628, 3, '安全协议', 'securityProtocol', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["PLAINTEXT","SSL","SASL_PLAINTEXT","SASL_SSL"],"default":"PLAINTEXT"}'),
       (629, 4, 'SASL机制', 'saslMechanism', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["PLAIN","SCRAM-SHA-256","SCRAM-SHA-512"]}'),
       (760, 5, '主题名称', 'topic', 'databridge_kafka_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入Kafka主题名称"}'),
       (761, 6, '消费者组', 'groupId', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入消费者组ID（输入模式）"}'),
       (762, 7, '分区数', 'partitions', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":1,"min":1,"max":100}'),
       (763, 8, '副本数', 'replicationFactor', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":1,"min":1,"max":10}'),
       (764, 9, '序列化器', 'serializer', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["StringSerializer","JsonSerializer","AvroSerializer"],"default":"JsonSerializer"}'),
       (765, 10, '压缩类型', 'compressionType', 'databridge_kafka_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["none","gzip","snappy","lz4","zstd"],"default":"none"}');
