-- HTTP配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (670, 1, '基础URL', 'baseUrl', 'databridge_http_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入HTTP基础URL"}'),
       (671, 2, '请求方法', 'method', 'databridge_http_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":true,"options":["GET","POST","PUT","DELETE"],"default":"POST"}'),
       (672, 3, '内容类型', 'contentType', 'databridge_http_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":true,"options":["application/json","application/x-www-form-urlencoded","text/plain"],"default":"application/json"}'),
       (673, 4, '认证类型', 'authType', 'databridge_http_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["none","basic","bearer","apikey"],"default":"none"}'),
       (674, 5, '认证令牌', 'authToken', 'databridge_http_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":false,"placeholder":"请输入认证令牌"}'),
       (675, 6, '超时时间', 'timeout', 'databridge_http_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":30000,"min":1000,"max":300000}'),
       (676, 7, '重试次数', 'retryTimes', 'databridge_http_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":3,"min":0,"max":10}'),
       (677, 8, '自定义头部', 'customHeaders', 'databridge_http_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"textarea","required":false,"placeholder":"请输入自定义HTTP头部（JSON格式）"}');
