-- InfluxDB配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (700, 1, '主机地址', 'host', 'databridge_influxdb_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入InfluxDB主机地址"}'),
       (701, 2, '端口', 'port', 'databridge_influxdb_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":8086,"min":1,"max":65535}'),
       (702, 3, '数据库名', 'database', 'databridge_influxdb_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入InfluxDB数据库名"}'),
       (703, 4, '用户名', 'username', 'databridge_influxdb_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入InfluxDB用户名（可选）"}'),
       (704, 5, '密码', 'password', 'databridge_influxdb_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":false,"placeholder":"请输入InfluxDB密码（可选）"}'),
       (705, 6, '保留策略', 'retentionPolicy', 'databridge_influxdb_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"default":"autogen","placeholder":"请输入保留策略"}'),
       (706, 7, '测量名', 'measurement', 'databridge_influxdb_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入测量名模板"}'),
       (707, 8, '批量大小', 'batchSize', 'databridge_influxdb_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":1000,"min":1,"max":10000}');
