-- Elasticsearch配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (710, 1, '主机地址', 'host', 'databridge_elasticsearch_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入Elasticsearch主机地址"}'),
       (711, 2, '端口', 'port', 'databridge_elasticsearch_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":9200,"min":1,"max":65535}'),
       (712, 3, '索引名', 'indexName', 'databridge_elasticsearch_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入Elasticsearch索引名"}'),
       (713, 4, '用户名', 'username', 'databridge_elasticsearch_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入Elasticsearch用户名（可选）"}'),
       (714, 5, '密码', 'password', 'databridge_elasticsearch_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":false,"placeholder":"请输入Elasticsearch密码（可选）"}'),
       (715, 6, '文档类型', 'docType', 'databridge_elasticsearch_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"default":"_doc","placeholder":"请输入文档类型"}'),
       (716, 7, '批量大小', 'batchSize', 'databridge_elasticsearch_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":1000,"min":1,"max":10000}'),
       (717, 8, '刷新策略', 'refreshPolicy', 'databridge_elasticsearch_fields', '', '', 'N', '0', 'admin', NOW(), '',
        NULL, '{"type":"select","required":false,"options":["none","wait_for","immediate"],"default":"none"}');
