<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-platform</artifactId>
        <version>4.2.0.RELEASE</version>
    </parent>
    <groupId>org.springblade</groupId>
    <artifactId>iot-bridge</artifactId>
    <packaging>pom</packaging>
    <version>4.2.0.RELEASE</version>

    <modules>
        <module>iot-bridge-core</module>
        <module>iot-bridge-plugin-jdbc</module>
        <module>iot-bridge-plugin-kafka</module>
        <module>iot-bridge-plugin-mqtt</module>
        <module>iot-bridge-plugin-http</module>
        <module>iot-bridge-plugin-iotdb</module>
        <module>iot-bridge-plugin-influxdb</module>
        <module>iot-bridge-starter</module>
        <module>iot-bridge-web</module>
    </modules>
</project>
