<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>iot-platform</artifactId>
        <groupId>org.springblade</groupId>
        <version>4.9.0.RELEASE</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>iot-link</artifactId>
    <name>${project.artifactId}</name>
    <description>设备集成服务模块</description>
    <packaging>pom</packaging>

    <modules>
        <module>iot-link-biz</module>
        <module>iot-link-controller</module>
        <module>iot-link-facade</module>
    </modules>
</project>
