package org.springblade.core.chatgpt.model.param;

import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * -----------------------------------------------------------------------------
 * File Name: OpenAiChatRequestParam
 * -----------------------------------------------------------------------------
 * Description:
 * OpenAiChatRequest
 * -----------------------------------------------------------------------------
 *
 * @author xiaonannet
 * @version 1.0
 * -----------------------------------------------------------------------------
 * Revision History:
 * Date         Author          Version     Description
 * --------      --------     -------   --------------------
 * 2023/12/12       xiaonannet        1.0        Initial creation
 * -----------------------------------------------------------------------------
 * @email 13733918655@163.com
 * @date 2023/12/12 23:20
 */
@Data
@Builder
public class OpenAiChatRequestParam implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     * The unique session ID generated by OpenAI.
     */
    private String id;

    /**
     * The model to use for this chat (e.g., gpt-3.5-turbo)
     */
    private String model;

    /**
     * Content of the message to be processed
     */
    private String content;

    /**
     * API Key for OpenAI
     */
    private List<String> apiKey;

    /**
     * API Host for OpenAI
     */
    private String apiHost;

}
