<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-components</artifactId>
        <version>4.2.0.RELEASE</version>
    </parent>

    <artifactId>iot-component-tcp</artifactId>
    <description>iot-component-tcp TCP 透传工业设备接入组件</description>
    <properties>
        <module.name>iot.component.tcp</module.name>
    </properties>

    <dependencies>
        <!-- IOT 组件核心 -->
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-component-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>module-iot-api</artifactId>
        </dependency>

        <!-- Vert.x MQTT & Netty -->
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mqtt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
    </dependencies>

</project>
