<?xml version="1.0" encoding="UTF-8"?>
<!-- TDS 实体：时序数据的 DTO/VO/Entity -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-entity</artifactId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <groupId>org.springblade</groupId>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-entity-tds</artifactId>
    <name>${project.artifactId}</name>
    <description>时序数据服务-实体模块</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-core-basic</artifactId>
        </dependency>


    </dependencies>

</project>
