<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>iot-rule</artifactId>
        <groupId>org.springblade</groupId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-rule-controller</artifactId>
    <name>${project.artifactId}</name>
    <description>规则引擎服务-控制器模块</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-rule-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-rule-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-core-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mqttsnet.basic</groupId>
            <artifactId>thinglinks-mvc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mqttsnet.basic</groupId>
            <artifactId>thinglinks-databridge-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mqttsnet.basic</groupId>
            <artifactId>thinglinks-condition-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-entity-link</artifactId>
        </dependency>
    </dependencies>
</project>
