<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springblade</groupId>
        <artifactId>iot-platform</artifactId>
        <version>4.2.0.RELEASE</version>
    </parent>
    <artifactId>iot-framework</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>iot-framework-common</module>
        <module>iot-framework-config</module>
        <module>iot-framework-core</module>
        <module>iot-framework-dm</module>
        <module>iot-framework-exception</module>
        <module>iot-framework-notice</module>
        <module>iot-framework-oss</module>
        <module>iot-framework-rocketmq</module>
    </modules>
</project>
