<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>iot-link-facade</artifactId>
        <groupId>org.springblade</groupId>
        <version>4.9.0.RELEASE</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>iot-link-cloud-impl</artifactId>
    <name>${project.artifactId}</name>
    <description>设备集成服务-Cloud实现模块</description>

    <dependencies>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>iot-link-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springblade</groupId>
            <artifactId>blade-core-boot</artifactId>
        </dependency>
    </dependencies>
</project>
