wxpay.appId=wxd5cc3ee551a8d47a
wxpay.appSecret=d3e7437a63d3ffae457020bbbb692489
wxpay.mchId=1700601193
wxpay.partnerKey=UzFfAgtgekIEAQBsu5La6EwstQy6ubaL
wxpay.certPath=apiclient_cert.p12
wxpay.domain=http://www.kaoyanbibei.net
