-- MySQL配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (621, 1, '主机地址', 'host', 'databridge_mysql_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入MySQL主机地址"}'),
       (622, 2, '端口', 'port', 'databridge_mysql_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":3306,"min":1,"max":65535}'),
       (623, 3, '用户名', 'username', 'databridge_mysql_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入数据库用户名"}'),
       (624, 4, '密码', 'password', 'databridge_mysql_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":true,"placeholder":"请输入数据库密码"}'),
       (625, 5, '数据库名', 'databaseName', 'databridge_mysql_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入数据库名称"}'),
       (770, 6, '字符集', 'charset', 'databridge_mysql_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["utf8","utf8mb4","latin1"],"default":"utf8mb4"}'),
       (771, 7, '连接超时', 'connectionTimeout', 'databridge_mysql_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":30000,"min":1000,"max":300000}'),
       (772, 8, '最大连接数', 'maxConnections', 'databridge_mysql_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":10,"min":1,"max":100}'),
       (773, 9, '表名前缀', 'tablePrefix', 'databridge_mysql_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入表名前缀（可选）"}'),
       (774, 10, '批量大小', 'batchSize', 'databridge_mysql_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":1000,"min":1,"max":10000}');
