-- MQTT配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (660, 1, '主机地址', 'host', 'databridge_mqtt_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入MQTT Broker地址"}'),
       (661, 2, '端口', 'port', 'databridge_mqtt_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":1883,"min":1,"max":65535}'),
       (662, 3, '用户名', 'username', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入MQTT用户名（可选）"}'),
       (663, 4, '密码', 'password', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":false,"placeholder":"请输入MQTT密码（可选）"}'),
       (664, 5, '客户端ID', 'clientId', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入客户端ID（可选）"}'),
       (665, 6, 'QoS等级', 'qos', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"select","required":false,"options":["0","1","2"],"default":"1"}'),
       (666, 7, '保持连接', 'keepAlive', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":60,"min":10,"max":3600}'),
       (667, 8, '清除会话', 'cleanSession', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"switch","required":false,"default":true}'),
       (668, 9, '订阅主题', 'subscribeTopic', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入订阅主题（输入模式）"}'),
       (669, 10, '发布主题', 'publishTopic', 'databridge_mqtt_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入发布主题（输出模式）"}');
