-- Redis配置字段
INSERT INTO `sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`,
                             `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`,
                             `update_time`, `remark`)
VALUES (680, 1, '主机地址', 'host', 'databridge_redis_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":true,"placeholder":"请输入Redis主机地址"}'),
       (681, 2, '端口', 'port', 'databridge_redis_fields', '', '', 'Y', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":true,"default":6379,"min":1,"max":65535}'),
       (682, 3, '密码', 'password', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"password","required":false,"placeholder":"请输入Redis密码（可选）"}'),
       (683, 4, '数据库索引', 'database', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":0,"min":0,"max":15}'),
       (684, 5, '连接超时', 'connectionTimeout', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":5000,"min":1000,"max":60000}'),
       (685, 6, '读取超时', 'readTimeout', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":3000,"min":1000,"max":60000}'),
       (686, 7, '最大连接数', 'maxConnections', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"number","required":false,"default":8,"min":1,"max":100}'),
       (687, 8, '键前缀', 'keyPrefix', 'databridge_redis_fields', '', '', 'N', '0', 'admin', NOW(), '', NULL,
        '{"type":"input","required":false,"placeholder":"请输入键前缀（可选）"}');
